DEBUG - 2025-01-22 06:51:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-01-22 06:51:36 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\YSL\artikel27\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\YSL\artikel27\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'artikel', 3306, '', 0)
#1 D:\YSL\artikel27\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\YSL\artikel27\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\YSL\artikel27\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\YSL\artikel27\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 D:\YSL\artikel27\vendor\codeigniter4\framework\system\BaseModel.php(713): CodeIgniter\Model->doFirst()
#6 D:\YSL\artikel27\app\Controllers\Auth.php(24): CodeIgniter\BaseModel->first()
#7 D:\YSL\artikel27\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Auth->autentikasi()
#8 D:\YSL\artikel27\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 D:\YSL\artikel27\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\YSL\artikel27\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 D:\YSL\artikel27\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\YSL\artikel27\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\YSL\artikel27\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('D:\\YSL\\artikel2...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\YSL\artikel27\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\YSL\artikel27\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\YSL\artikel27\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\YSL\artikel27\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\YSL\artikel27\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 D:\YSL\artikel27\vendor\codeigniter4\framework\system\BaseModel.php(713): CodeIgniter\Model->doFirst()
#5 D:\YSL\artikel27\app\Controllers\Auth.php(24): CodeIgniter\BaseModel->first()
#6 D:\YSL\artikel27\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Auth->autentikasi()
#7 D:\YSL\artikel27\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 D:\YSL\artikel27\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\YSL\artikel27\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 D:\YSL\artikel27\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\YSL\artikel27\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\YSL\artikel27\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('D:\\YSL\\artikel2...')
#13 {main}
CRITICAL - 2025-01-22 06:51:36 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: POST, Route: autentikasi]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `pengguna`
WHERE `username` = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Auth.php(24): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->autentikasi()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\YSL\\artikel27\\public\\index.php')
